### ISSUE TITLE
Button clicks are sometimes ignored 

### ISSUE THREAD

**Issue by Stvad** [mlava/yesterday-tomorrow#2] opened 2023-02-24 07:02 UTC
This is great, thank you for building it! Unfortunately buttons work very unreliably for me :( sometimes clicking them works and sometimes is ignored. 

On skimming the code (and from my prev experience) my guess is that it may be because plugin is relying on Date page uid being in the form like `02-23-2023` which doesn't necessarily hold (sometimes it's just an random char uid like other pages).  

The way I reliably obtain current/prev/next days in other plugins I've built is by doing date page search by name

**Comment by mlava** [comment] 2023-02-25 08:17
Hi @Stvad.
I haven't seen a DNP without a dated uid. I also haven't seen this issue with buttons not working.
I'm happy to change how the dates are handled, but can you point me to an example of this happening? Or show me a console log of it happening? 
Cheers!

**Comment by Stvad** [comment] 2023-03-04 13:48
I'm not sure what is the exact condition that creates them (I think it's something like referencing a page before navigating to it through main calendar widget)

In my database the uid for March 1st is `i0_ZDNcow` 
When trying to use the plugin to go back to it - the following error is thrown in the console:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/81347/222906038-0b9d349e-f83d-4bd1-bc68-f0acd996e5f4.png">

**Comment by mlava** [comment] 2023-03-05 21:25
Are all of your dated pages like that, or do some have the more usual '03-07-2023' form?

Are there other extensions/roamjs that are creating date pages for you? The docs state DNP should be created with the date format: https://roamresearch.com/#/app/developer-documentation/page/_wF2U1Itr

**Comment by mlava** [comment] 2023-03-06 04:57
I've pushed a fix that handles the usual uid and atypical uid. This should fix your problem.
I don't understand how you're even creating uids like that though, as RR natively creates a MM-DD-YYYY uid for DNPs. I'm not sure if it's an extension that's miscoded, or some roam/js?
I can't reproduce in my graph, but think this fix should work anyway.
Cheers!

**Comment by Stvad** [comment] 2023-03-06 06:09
thank you!
most of my date pages have the date-format UIDs, but I'd say at least 15% have the alphanumeric uids

I don't know exactly why, but my guess is that it's from me referencing the date pages by name before they exist (e.g. writing `[[March 6th, 2025]]` before that date was created by Roam

**Comment by mlava** [comment] 2023-03-10 01:23
@Stvad 
I'm pretty sure this is fixed in the version approved yesterday. Could you let me know if not?
Cheers!

**Comment by Stvad** [comment] 2023-03-14 05:35
@mlava thanks for looking into this! It doesn’t crash anymore but doesn’t quite work correctly either:
- When I go to March 1st (the day with alphanum UID) and go forwards or backwards from it - the plugin jumps to March 13 or March 15 (yesterday or tomorrow respectively) instead of going to Feb 28th or March 2nd as expected. I suspect that’s because the code responsible for whether the current page is the date page still expect date-like uids!

**Comment by mlava** [comment] 2023-03-19 21:25
ok, back to the drawing board...

**Comment by mlava** [comment] 2023-03-22 06:04
Pretty sure it's fixed in https://github.com/Roam-Research/roam-depot/pull/615

**Closed as completed** 2023-03-22 06:05 UTC

**Comment by mlava** [comment] 2023-04-13 21:53
This update is finally live @Stvad and should fix the forward/backward issue for non-standard DNP uids.
Cheers

**Comment by Stvad** [comment] 2023-04-17 23:25
Thank you!

**Comment by Stvad** [comment] 2023-05-10 23:45
I think there were a regression on this. It's failing for the alphanumeric uuid (today's uuid is `Yu59cidGv`)
![image](https://github.com/mlava/yesterday-tomorrow/assets/81347/3f5f748a-8201-47b5-92ce-38bdefd824cc)

Though interesting navigating from yesterday to today with the "next" button still works!
